# Site settings
title: "Vipul Resume"
description: "A resume template for Vipul Jain."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Vipul Jain"
resume_title:                   "Data Scientist/Analyst"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "007.vipul.j@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+61 4344-43228"
resume_contact_address:         "5/1 Johnston Street, Newport, Victoria, Australia 3015"

resume_header_contact_info:     "5/1 Johnston Street, Newport, Victoria, Australia 3015 • +61 4344-43228 • 007.vipul.j@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Data Scientist and Analyst who likes to solve problems using data+code. Proficient in the field of Machine Learning and Artificial Intelligence. Other interests include building Time Series Models, Data Visualization and Sales & Profit Forecasting.</p><p>Respected for organizational and interpersonal aptitudes, implementation of strategic initiatives, project management and results-focused interactions across organization.</p><p>Pursuing Master of Data Science, RMIT University, following an interest in Machine Learning and Artificial Intelligence with <b>Full-Time working rights in Australia</b>.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/Bloodphilic"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/vipul-jain-a3115944/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
